
//auth
export const USER_LOGIN_SUCCESS = 'user_login_success';
export const USER_LOGOUT = 'USER_LOGOUT';
export const FORGOT_PW_START = 'FORGOT_PW_START';
export const FORGOT_PW_ERROR = 'FORGOT_PW_ERROR';
export const FORGOT_PW_SUCCESS = 'FORGOT_PW_SUCCESS';
export const RESET_AUTH_DATA = 'RESET_AUTH_DATA';
export const LOAD_ECASH_CONFIG = 'LOAD_ECASH_CONFIG';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const ACTIVATE_MY_ECASH = 'ACTIVATE_MY_ECASH';
export const IS_GETTING_REFERRAL_DETAILS = 'IS_GETTING_REFERRAL_DETAILS';
export const SAVE_QUICK_SERVICES = 'SAVE_QUICK_SERVICES';

