


export const START_LOAD_LOANS = 'START_LOAD_LOANS';
export const END_LOAD_LOANS = 'END_LOAD_LOANS';
export const LOAD_LOANS = 'LOAD_LOANS';
export const LOAD_RUNNING_LOAN = 'LOAD_RUNNING_LOAN';
export const LOAD_LOAN_DETAILS = 'LOAD_LOAN_DETAILS';
export const LOAD_LOAN_OPTIONS = 'LOAD_LOAN_OPTIONS';


export const UPDATE_USER_LOAN_DETAILS = 'UPDATE_USER_LOAN_DETAILS';
export const CLEAR_LOAN_DETAILS = 'CLEAR_LOAN_DETAILS';


