
//loan
export const LOAD_HISTORY = 'LOAD_HISTORY';
export const LOAD_ACTIVE_CURRENT_LOAN = 'LOAD_ACTIVE_CURRENT_LOAN';
export const START_LOAD_CURRENT_LOAN = 'START_LOAD_CURRENT_LOAN';
export const END_LOAD_CURRENT_LOAN = 'END_LOAD_CURRENT_LOAN';
export const LOAD_SERVICE_OPTIONS = 'LOAD_SERVICE_OPTIONS';
export const START_LOAD_HISTORY = 'START_LOAD_HISTORY';
export const END_LOAD_HISTORY = 'END_LOAD_HISTORY';
export const LOAD_AGENT_DASHBOARD = 'LOAD_AGENT_DASHBOARD';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';

export const START_TRANSACTION_LOAD_HISTORY = 'START_TRANSACTION_LOAD_HISTORY';
export const END_TRANSACTION_LOAD_HISTORY = 'END_TRANSACTION_LOAD_HISTORY';
export const LOAD_TRANSACTION_HISTORY = 'LOAD_TRANSACTION_HISTORY';


export const START_GET_REFEREES = 'START_GET_REFEREES';
export const END_GET_REFEREES = 'END_GET_REFEREES';
export const LOAD_REFEREES = 'LOAD_REFEREES';
export const CHANGE_USER_TYPE = 'CHANGE_USER_TYPE'



//Wallet

export const LOAD_WALLET = 'LOAD_WALLET';
export const LOAD_SAVINGS_WALLET = 'LOAD_SAVINGS_WALLET';
export const LOAD_AGENT_WALLET = 'LOAD_AGENT_WALLET';



//home - not being used at the moment
//new

export const START_LOAD_DASHBOARD = 'START_LOAD_DASHBOARD';
export const END_LOAD_DASHBOARD = 'END_LOAD_DASHBOARD';
export const LOAD_DASHBOARD = 'LOAD_DASHBOARD';
export const LOAD_BANKS = 'LOAD_BANKS';


