
//banks
export const LOAD_SYSTEM_BANKS = 'LOAD_SYSTEM_BANKS';
export const LOAD_SYSTEM_LOAN_PURPOSES = 'LOAD_SYSTEM_LOAN_PURPOSES';


export const START_LOAD_WALLET = 'START_LOAD_WALLET';
export const END_LOAD_WALLET = 'END_LOAD_WALLET';
export const LOAD_WALLET = 'LOAD_WALLET';

export const LOAD_WALLET_TRANSACTIONS = 'LOAD_WALLET_TRANSACTIONS';




