

export const LOAD_SAVINGS_PRODUCTS = 'LOAD_SAVINGS_PRODUCTS';
export const LOAD_SAVINGS_COLLECTIONS = 'LOAD_SAVINGS_COLLECTIONS';
export const LOAD_SAVINGS_FREQUENCIES = 'LOAD_SAVINGS_FREQUENCIES';
export const LOAD_SAVINGS_REPAYMENT_METHODS = 'LOAD_SAVINGS_REPAYMENT_METHODS';


export const LOAD_SAVINGS = 'LOAD_SAVINGS';
export const START_LOAD_SAVINGS = 'START_LOAD_SAVINGS';
export const END_LOAD_SAVINGS = 'END_LOAD_SAVINGS';



export const UPDATE_SAVINGS_DETAILS = 'UPDATE_SAVINGS_DETAILS';
export const RESET_SAVINGS_DETAILS = 'RESET_SAVINGS_DETAILS';



